#!/usr/bin/env sh

cwd=$(dirname "$0")

source ${cwd}/../utils.sh

template_path=$cwd
output_path="$template_path/../.."

#---

gitconfig_contents=$(cat "$template_path/gitconfig.tmpl")
if command_exists "git"; then
  current_git_user_name=$(git config user.name)
  current_git_user_email=$(git config user.email)
else
  current_git_user_name=""
  current_git_user_email=""
fi

git_user_name=$(prompt "Git user name" "$current_git_user_name")
git_user_email=$(prompt "Git user email" "$current_git_user_email")

result=$(
  echo "$gitconfig_contents" |
    sed -e "s/@git.name@/${git_user_name}/g" |
    sed -e "s/@git.email@/${git_user_email}/g"
)

echo "$result" >"$output_path/dot-gitconfig"
