#[Sunsetr configuration]
backend = "auto"                # Backend to use: "auto", "hyprland" or "wayland"
start_hyprsunset = true         # Set true if you're not using hyprsunset.service
startup_transition = true       # Enable smooth transition when sunsetr starts
startup_transition_duration = 5 # Duration of startup transition in seconds (1-60)
night_temp = 3300               # Color temperature after sunset (1000-20000) Kelvin
day_temp = 5500                 # Color temperature during day (1000-20000) Kelvin
night_gamma = 95                # Gamma percentage for night (0-100%)
day_gamma = 100                 # Gamma percentage for day (0-100%)
update_interval = 60            # Update frequency during transitions in seconds (10-300)
transition_mode = "start_at"    # Select: "geo", "finish_by", "start_at", "center"

#[Manual transitions]
sunset = "17:00:00"             # Time to transition to night mode (HH:MM:SS) - ignored in geo mode
sunrise = "07:00:00"            # Time to transition to day mode (HH:MM:SS) - ignored in geo mode
transition_duration = 45        # Transition duration in minutes (5-120)

#[Geolocation-based transitions]
# Location: Berlin
latitude = 52.52
longitude = 13.4
